# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c78c204c06ee7b300bae367819b43a43f1efd17028b954e74cd88a0bdd6916f8c5294d1f5ecbc0cfd4d7f96b6df73e0723a5a9d6ea5f1e6e8775b3b34d224a1

test:
  secret_key_base: 28d315c09cc19838b249c3400153bca44d2fe50519c2d6a6604b6e1f34d0d0a22553ff45aeb5b7698939547637c62542baf5b330672eab3c6403ec6f7896ee99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
